[package]
name = "nlp01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31"
rand = "0.8.5"
num = "0.4.0"
num-traits = "0.2.15"
common = { path = "../common" }
